#!/bin/bash

set -e

STATSD=/dev/udp/127.0.0.1/8125
STATEDIR=/var/lib/pmipt

mkdir -p ${STATEDIR}
find ${STATEDIR} -maxdepth 1 -type f -name changes.\* -mtime +7 -delete
now=$(date "+%Y%m%d%H%M%S")
changes=${STATEDIR}/changes.${now}

iptables-save | pmipt-changes /etc/pmipt.conf - > ${changes}

set +e 

iptables-restore -t -v -n < ${changes}
if [[ $? -ne 0 ]]; then
    logger -p user.error -t pmipt "${changes} does not test cleanly"
    echo -n "pmipt.error.check:1|c" >${STATSD}
    exit 1
else
    echo -n "pmipt.success.check:1|c" >${STATSD}
fi

iptables-restore -n < ${changes}
if [[ $? -ne 0 ]]; then
    logger -p user.error -t pmipt "${changes} does not apply cleanly"
    echo -n "pmipt.error.apply:1|c" >${STATSD}
    exit 1
else
    logger -p user.notice -t pmipt "${changes} applied cleanly"
    echo -n "pmipt.success.apply:1|c" >${STATSD}
fi
