import pytest
import yaml


@pytest.fixture
def raw_pmipt_config():
    """PMIPTConfig dictionary as might be encoded into YAML."""
    config = {
        "nat": {
            "PREROUTING": {
                "rules": [
                    "--dst 10.0.0.1 -p udp --dport 53 -j DNAT --to-destination 127.0.0.1:53",
                    "--dst 10.0.0.2 -j DNAT --to-destination 10.0.0.3",
                ],
            },
            "OUTPUT": {
                "rules": [
                    "--src 127.0.0.93 -j MARK --set-mark 0x10901",
                ],
            },
            "PMIPT[mychain]": {
                "rules": [
                    "--dst 2.2.2.2/30 -p tcp --dport 80 -j DNAT --to-destination 10.9.9.9",
                    "--dst 3.3.3.3/32 -p tcp --dport 443 -j SNAT --to 1.2.3.4",
                ],
            },
        },
        "filter": {
            "OUTPUT": {
                "rules": [
                    "--dst 2.2.2.2/30 -p tcp --dport 80 -j DROP",
                    "--dst 3.3.3.3/32 -p tcp --dport 443 -j ACCEPT",
                ],
            },
            "PMIPT[mychain]": {
                "rules": [
                    "--dst 127.0.0.93 -m mark --mark 0x10901 -j ACCEPT",
                    "--dst 127.0.0.46 -m mark ! --mark 0x10901 -j DROP",
                ],
            },
        },
    }
    return config


@pytest.fixture
def raw_iptables_save():
    """Raw iptables-save output."""
    save = """
# Generated by iptables-save v1.4.21 on Sat May 13 00:39:40 2017
*mangle
:PREROUTING ACCEPT [133569:21296943]
:INPUT ACCEPT [133569:21296943]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [132691:15226664]
:POSTROUTING ACCEPT [132691:15226664]
:PMIPT[mark-local] - [139:4663]
-A PMIPT[mark-local] -d 9.9.9.0/24 -J MARK --set-mark 0x10901 -m comment --comment "PMIPT[225b92c4f0134c25f3ead0b791bb2d0b441a19e49adc3d52c4fcefece1c3ec71]"
-A PMIPT[mark-local] -d 3.3.3.0/24 -J MARK --set-mark 0x10901 -m comment --comment "PMIPT[12be011351c369c7031e0c7b48bcc0e498cbb668ac65c51c361a8481df5b82b8]"
COMMIT
# Completed on Sat May 13 00:39:40 2017
# Generated by iptables-save v1.4.21 on Sat May 13 00:39:40 2017
*nat
:PREROUTING ACCEPT [391:24897]
:INPUT ACCEPT [391:24897]
:OUTPUT ACCEPT [3128:220044]
:POSTROUTING ACCEPT [3128:220044]
:DOCKER - [0:0]
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -s 172.18.0.0/16 ! -o docker0 -j MASQUERADE
-A INPUT --src 0.0.0.0/0 -j ACCEPT -m comment --comment "PMIPT[03c99a2373cdbc8c1838457777520ab9f925f5119a24e1931a534a871ba6d1d3]"
-A DOCKER -i docker0 -j RETURN
COMMIT
# Completed on Sat May 13 00:39:40 2017
# Generated by iptables-save v1.4.21 on Sat May 13 00:39:40 2017
*filter
:INPUT ACCEPT [120:9964]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [110:11164]
:DOCKER - [0:0]
:DOCKER-ISOLATION - [0:0]
-A INPUT -d 8.8.4.4/32 -j ACCEPT -m comment --comment "allow google dns for some reason"
-A INPUT -d 8.8.8.8/32 -j ACCEPT -m comment --comment "PMIPT[8a3a75256e8d2f4ed91447e00a6e7be774b545603064cf72ddfa9080ef0ed20f]"
-A FORWARD -j DOCKER-ISOLATION
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A DOCKER-ISOLATION -j RETURN
COMMIT
# Completed on Sat May 13 00:39:40 2017
"""
    return save
